#pragma once
void testGetteriCheltuiala();
void testSetteriCheltuiala();
void testAddCheltuiala();
void testDeleteCheltuiala();
void testGetSize();
void testUpdateCheltuiala();
void testAddCheltuialaS();
void testDeleteCheltuialaS();
void testUpdateCheltuialaS();